random-filter-s:
  fdufilterdiskann:
   docker-tag: neurips23-filter-fdufilterdiskann
   module: neurips23.filter.fdufilterdiskann.fdufilterdiskann
   constructor: fdufilterdiskann
   base-args: ["@metric"]
   run-groups:
    base:
     args: |
      [{"R":2, "L":10, "buildthreads":16, "alpha":1.2}]
     query-args: |
      [{"Ls":10, "T":1, "threshold_1":20000, "threshold_2":40000}]
yfcc-10M:
  fdufilterdiskann:
   docker-tag: neurips23-filter-fdufilterdiskann
   module: neurips23.filter.fdufilterdiskann.fdufilterdiskann
   constructor: fdufilterdiskann
   base-args: ["@metric"]
   run-groups:
    base:
     args: |
      [{"R":60, "L":80, "buildthreads":16, "alpha":1.0}]
     query-args: |
      [
        {"Ls":11, "T":16, "threshold_1":53500, "threshold_2":41000},
        {"Ls":11, "T":16, "threshold_1":53500, "threshold_2":41100},
        {"Ls":11, "T":16, "threshold_1":53500, "threshold_2":41200},
        {"Ls":11, "T":16, "threshold_1":53500, "threshold_2":41300},
        {"Ls":11, "T":16, "threshold_1":53500, "threshold_2":41400},
        {"Ls":12, "T":16, "threshold_1":53500, "threshold_2":41000},
        {"Ls":12, "T":16, "threshold_1":53500, "threshold_2":51100},
        {"Ls":12, "T":16, "threshold_1":53500, "threshold_2":41200},
        {"Ls":12, "T":16, "threshold_1":53500, "threshold_2":41300},
        {"Ls":12, "T":16, "threshold_1":53500, "threshold_2":41400}
      ]
