random-filter-s:
    falconn-5t-0001s-unnorm:
      docker-tag: falconn
      module: neurips23.filter.falconn-5t-0001s-unnorm.falconn
      constructor: FALCONN
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"indexkey": "IVF1024,SQ8"}]
          query-args: |
            [
              {
                "nprobe": 5
              },
              {
                "nprobe": 10
              },
              {
                "nprobe": 20
              }
            ]
yfcc-10M:
    falconn-5t-0001s-unnorm:
      docker-tag: falconn
      module: neurips23.filter.falconn-5t-0001s-unnorm.falconn
      constructor: FALCONN
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"indexkey": "IVF1024,SQ8"}]
          query-args: |
            [
              {
                "nprobe": 5
              },
              {
                "nprobe": 10
              },
              {
                "nprobe": 20
              },
              {
                "nprobe": 50
              },
              {
                "nprobe": 100
              },
              {
                "nprobe": 200
              },
              {
                "nprobe": 500
              }
            ]
