random-filter-s:
    falconn:
      docker-tag: falconn
      module: neurips23.filter.falconn.falconn
      constructor: FALCONN
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"indexkey": "IVF1024,SQ8"}]
          query-args: |
            [
              {
                "nprobe": 50
              },
              {
                "nprobe": 75
              },
              {
                "nprobe": 100
              }
            ]
yfcc-10M:
    falconn:
      docker-tag: falconn
      module: neurips23.filter.falconn.falconn
      constructor: FALCONN
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"indexkey": "IVF1024,SQ8"}]
          query-args: |
            [
              {
                "nprobe": 50
              }
            ]
