random-filter-s:
    falconn:
      docker-tag: neurips23-filter-falconn
      module: neurips23.filter.falconn.falconn
      constructor: FALCONN
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"indexkey": "IVF1024,SQ8"}]
          query-args: |
            [
              {
                "nprobe": 100
              },
              {
                "nprobe": 125
              },
              {
                "nprobe": 150
              }
            ]
random-filter-yfcc:
    falconn:
      docker-tag: neurips23-filter-falconn
      module: neurips23.filter.falconn.falconn
      constructor: FALCONN
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"indexkey": "IVF1024,SQ8"}]
          query-args: |
            [
              {
                "nprobe": 100
              },
              {
                "nprobe": 125
              },
              {
                "nprobe": 150
              }
            ]
yfcc-10M:
    falconn:
      docker-tag: neurips23-filter-falconn
      module: neurips23.filter.falconn.falconn
      constructor: FALCONN
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"indexkey": "IVF1024,SQ8"}]
          query-args: |
            [
              {
                "nprobe": 50
              }
            ]
