yfcc-10M:
    parlayivf:
      docker-tag: neurips23-filter-parlayivf
      module: neurips23.filter.parlayivf.parlayivf
      constructor: ParlayIVF
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [
            {"cluster_size": 2500, 
              "T": 8,
              "cutoff": 15000,
              "max_iter": 20
            },
            {"cluster_size": 1000, 
              "T": 8,
              "cutoff": 15000,
              "max_iter": 20
            },
            {"cluster_size": 500, 
              "T": 8,
              "cutoff": 15000,
              "max_iter": 20
            },
            {"cluster_size": 5000, 
              "T": 8,
              "cutoff": 15000,
              "max_iter": 20
            }]
          query-args: |
            [{"target_points": 1000,
              "tiny_cutoff": 0,
              "sq_target_points": 100},
              {"target_points": 1000,
              "tiny_cutoff": 500,
              "sq_target_points": 100},
              {"target_points": 1000,
              "tiny_cutoff": 1000,
              "sq_target_points": 100},
              {"target_points": 10000,
              "tiny_cutoff": 0,
              "sq_target_points": 500},
              {"target_points": 10000,
              "tiny_cutoff": 500,
              "sq_target_points": 500},
              {"target_points": 10000,
              "tiny_cutoff": 1000,
              "sq_target_points": 500},
              {"target_points": 10000,
              "tiny_cutoff": 1000,
              "sq_target_points": 1000},
              {"target_points": 10000,
              "tiny_cutoff": 500,
              "sq_target_points": 1000},
              {"target_points": 10000,
              "tiny_cutoff": 1000,
              "sq_target_points": 2000},
              {"target_points": 10000,
              "tiny_cutoff": 1000,
              "sq_target_points": 4000},]
             
             
