yfcc-10M:
    parlayivf:
      docker-tag: neurips23-filter-parlayivf
      module: neurips23.filter.parlayivf.parlayivf
      constructor: ParlayIVF
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"cluster_size": 2500, 
              "T": 8,
              "cutoff": 20000,
              "max_iter": 40,
              "weight_classes": [50000, 300000],
              "build_params": [{"max_degree": 8,
                                "limit": 500,
                                "alpha": 1.175},
                              {"max_degree": 10,
                               "limit": 500,
                               "alpha": 1.175},
                              {"max_degree": 12,
                               "limit": 500,
                               "alpha": 1.175}]
            }]
          query-args: |
            [{"target_points": 15000,
              "tiny_cutoff": 1500,
              "beam_widths": [80, 90, 100]
              },
              {"target_points": 15000,
               "tiny_cutoff": 0,
               "beam_widths": [80, 90, 100]
               },
               {"target_points": 15000,
              "tiny_cutoff": 1500,
              "beam_widths": [100, 100, 100]
              },
              {"target_points": 15000,
               "tiny_cutoff": 0,
               "beam_widths": [100, 100, 100]
              },
              {"target_points": 15000,
               "tiny_cutoff": 1500,
               "beam_widths": [90, 90, 90]
              },
              {"target_points": 15000,
               "tiny_cutoff": 0,
               "beam_widths": [90, 90, 90]
              },
              {"target_points": 15000,
               "tiny_cutoff": 1500,
               "beam_widths": [80, 80, 80]
              },
              {"target_points": 15000,
               "tiny_cutoff": 0,
               "beam_widths": [80, 80, 80]
              },
              {"target_points": 15000,
               "tiny_cutoff": 1500,
               "beam_widths": [80, 75, 80]
              },
              {"target_points": 15000,
               "tiny_cutoff": 0,
               "beam_widths": [80, 75, 80]
              }
              {"target_points": 15000,
               "tiny_cutoff": 1500,
               "beam_widths": [80, 75, 75]
              },
              {"target_points": 15000,
               "tiny_cutoff": 0,
               "beam_widths": [80, 75, 75]
              }]
                   