yfcc-10M:
    parlayivf:
      docker-tag: neurips23-filter-parlayivf
      module: neurips23.filter.parlayivf.parlayivf
      constructor: ParlayIVF
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"cluster_size": 2500, 
              "T": 8,
              "cutoff": 30000,
              "max_iter": 40
            },
            {"cluster_size": 1000, 
              "T": 8,
              "cutoff": 50000,
              "max_iter": 40
            }]
          query-args: |
            [{"target_points": 10000,
              "tiny_cutoff": 1000
              },
              {"target_points": 20000,
              "tiny_cutoff": 500
              }]
             
             
