yfcc-10M:
  falconn-5t-0001s-1i:
    docker-tag: falconn
    module: neurips23.filter.falconn.falconn
    constructor: FALCONN
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [
            {
              "tables": 5,
              "sl_threshold": 0.0001,
              "iterations": 1,
              "normalize": false
            }
          ]
        query-args: |
          [
            {
              "nprobe": 5
            },
            {
              "nprobe": 10
            }
          ]
  falconn-5t-0001s-2i:
    docker-tag: falconn
    module: neurips23.filter.falconn.falconn
    constructor: FALCONN
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [
            {
              "tables": 5,
              "sl_threshold": 0.0001,
              "iterations": 2,
              "normalize": false
            }
          ]
        query-args: |
          [
            {
              "nprobe": 5
            },
            {
              "nprobe": 10
            }
          ]
  falconn-5t-0001s-3i:
    docker-tag: falconn
    module: neurips23.filter.falconn.falconn
    constructor: FALCONN
    base-args: ["@metric"]
    run-groups:
      base:
        args: |
          [
            {
              "tables": 5,
              "sl_threshold": 0.0001,
              "iterations": 3,
              "normalize": false
            }
          ]
        query-args: |
          [
            {
              "nprobe": 5
            },
            {
              "nprobe": 10
            }
          ]
